=== arohan0929/sysML-training-data/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "enum": [
                "Requirement Diagram",
                "Block Definition Diagram",
                "Internal Block Diagram",
                "Parametric Diagram",
                "Package Diagram",
                "Activity Diagram",
                "Sequence Diagram",
                "State Machine Diagram",
                "Use Case Diagram"
            ],
            "description": "The name of the SysML block"
        },
        "abbreviation": {
            "type": "string",
            "description": "The abbreviation of the SysML block"
        },
        "description": {
            "type": "string",
            "description": "The description of the SysML block"
        },
        "purpose": {
            "type": "string",
            "description": "The purpose of the SysML block"
        },
        "notations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "examples": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "bestPracticesPatterns": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "The best practices and patterns of the SysML block"
        },
        "antiPatterns": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "The anti-patterns of the SysML block"
        }
    },
    "required": [
        "name",
        "abbreviation",
        "description",
        "purpose",
        "notations",
        "bestPracticesPatterns",
        "antiPatterns"
    ]
}

=== arohan0929/sysML-training-data/block_definition_diagram.json
{
    "$schema": "./schema.json",
    "name": "Block Definition Diagram",
    "abbreviation": "bdd",
    "description": "The purpose of a block definition diagram is to display model elements such as blocks, actors, value types, constraint blocks, flow specifications and interfaces that can serve as other model elements that appear on the other eight kinds of SysML diagrams. Elements that appear on a BDD are known as elements of definition. You display the relationships between elements of definition with structural relationships such as associations, generalizations, and dependencies. With these relationships, you often create BDDs that convey decomposition and type classification. The model element type that the diagram frame represents can be any of the following: package, model, modelLibrary, view, block, or constraintBlock. ",
    "purpose": "",
    "notations": [
        {
            "name": "parts",
            "description": "There are part properties listed in the parts compartment of a block. A part property represents the structure that's internal to a block. A block is composed of its part properties and this relationship conveys ownership. When you list a part property in the parts compartment of a block, it appears as a string with the following format: <part name> : <type> [<multiplicity>] where the multiplicity is how many of the part exist within the block. If you want the part property to represent an unconstrained number of instances, you can set the multiplicity to 0..*. If no multiplicity is shown for a part property, the default is 1. When a part property has a multiplicity with an upper bound greater than 1 (e.g., 1..2, 0..10,*), we refer to that part property as a collection. ",
            "examples": ["eps : Electrical Power Subsystem [1]", "backupComputer: Flight Computer [1..2]"]
        },
        {
            "name": "references",
            "description": "A reference property is listed in the references compartment of a block and represents a structure that's external to a block. A reference property indicates a relationship where a block relies on an external structure to fulfill a purpose, such as delivering data or providing a service. This suggests that there is a link between them."
        }
    ],
    "bestPracticesPatterns": [
        "",
        ""
    ],
    "antiPatterns": [
        "",
        ""
    ]
}
